train_data_dir: "/mnt/c/Users/fraca/Documents/GitHub/crnn-lid/train_data_dir/training.csv"
validation_data_dir: "/mnt/c/Users/fraca/Documents/GitHub/crnn-lid/validation_data_dir/validation.csv"
test_data_dir: "/mnt//Users/fraca/Documents/GitHub/crnn-lid/test_data_dir/testing.csv"

batch_size: 16
learning_rate: 0.0005
num_epochs: 2

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
input_shape: [129, 500, 1]

model: "topcoder_crnn_finetune" # _finetune"

segment_length: 10  # number of seconds each spectogram represents
pixel_per_second: 50

label_names: ["EN", "DE"]
num_classes: 2

# label_names: ["EN", "DE", "FR", "ES", "CN", "RUS"]
# num_classes: 6